apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.vault3_configmap.name }}
  labels:
    app: {{ .Values.VAULT_3_APP_NAME }}
data:
  vault-config.hcl: |
    storage "raft" {
      path    = "/vault/raft"
      node_id = "vault_3"
      retry_join {
        leader_api_addr = "http://{{ .Values.vault1_cluster_ip.name }}:8200"
      }
    }
    listener "tcp" {
      address = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable = true
    }
    ui = true
    disable_mlock = true
    api_addr = "http://{{ .Values.vault3_cluster_ip.name }}:8200"
    cluster_addr = "http://{{ .Values.vault3_cluster_ip.name }}:8201"